---
abstract: 'accept4(2) bindings for Perl5'
author:
  - fb7ee91d9b089b78786fbb>
build_requires:
  Test::More: 0.98
  Test::TCP: 2.01
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Devel::CheckCompiler: 0.03
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.7.0, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Linux-Socket-Accept4
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Linux::Socket::Accept4:
    file: lib/Linux/Socket/Accept4.pm
    version: 0.01
requires:
  Exporter: 0
  parent: 0
  perl: 5.010001
resources:
  bugtracker: https://github.com/tokuhirom/Socket-Accept4/issues
  homepage: https://github.com/tokuhirom/Socket-Accept4
  repository: git://github.com/tokuhirom/Socket-Accept4.git
version: 0.01
x_contributors:
  - 'Masahiro Nagano <kazeburo@gmail.com>'
  - 'Syohei YOSHIDA <syohex@gmail.com>'
  - 'Tokuhiro Matsuno <tokuhirom@gmail.com>'
